export type UserData = {
    isEditedByUser: boolean;
    cmHeight: number;
    currentKgWeight: number;
    goalKgWeight: number;
    selectedSex: string;
    currentGoals: string[];
    healthConditions: string[];
    foodAtTheMoment: string[];
    foodScenario: string[];
    foodCuisines: string[];
    foodKinds: string[];
    foodAvoidProteins: string[];
    foodAvoidOthers: string[];
    foodBudget: string;
    basicActivities: string;
    pastPains: string;
    foodCookTime: string;
    foodCookSkills: string;
    foodCookCarb: string;
    foodCookProtein: string;
    mealsCount: number;
    lunchLeftovers: string;
};